- name: disable the nodejs -18  
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable the nodejs -20 
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install the nodejs 
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: create the user expense 
  ansible.builtin.user:
    name: expense 
    state: present

- name: create the app directory
  ansible.builtin.file:
    path: /app
    state: directory
    
- name: downlode the backend code and unzip in /app
  ansible.builtin.unarchive:
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
    dest: /app
    remote_src: yes


