- name: disable the nodejs -18  
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable the nodejs -20 
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install the nodejs 
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - nodejs
    - mysql 

- name: create the user expense 
  ansible.builtin.user:
    name: expense 
    state: present

- name: create the app directory
  ansible.builtin.file:
    path: /app
    state: directory
    
- name: downlode the backend code and unzip in /app
  ansible.builtin.unarchive:
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
    dest: /app
    remote_src: yes

- name: install dependencies 
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: copy the backend  services 
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service 
    remote_src: yes 

- name : load the schema 
  community.mysql.mysql_db:
    login_host: "{{ login_host }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    target: /app/schema/backend.sql
    state: import 
    name: all 

- name: daemon reload
  ansible.builtin.systemd:
    daemon_reload: true 

- name: enable and start the nodejs
  ansible.builtin.service: 
    name: nodejs 
    state: started
    enabled: yes 

