- name: install the nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: enable and start the nginx service 
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes 
- name: remove the default content 
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent 

- name: create the html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory 

- name: downlode and unzip the frontend code 
  ansible.builtin.get_url:
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /usr/share/nginx/html

- name: tamplate the expense conf file
  ansible.builtin.template:
    src: expense.conf.js 
    dest: /etc/nginx/default.d/expense.conf
  notify:
    - restart nginx 




