- name: install mysql-server 
  ansible.builtin.dnf: 
    name: mysql-server
    state: latest

- name: start and enable the mysqld server 
  ansible.builtin.service:
    name: mysqld 
    state: started 
    enabled: yes 

- name : check the password already setup or not 
  community.mysql.mysql_info:
    login_host: "{{ login_host }}"
    login_user: root 
    login_password: "{{ mysql_root_password }}"
    filter: version
  ignore_errors: yes 
  register: mysql_info 

- name: print the mysql info 
  ansible.builtin.debug:
    msg: "mysql info is {{ mysql_info }}"

- name: setupo the mysql root password 
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ mysql_root_password }}
  